### ISSUE TITLE
오토매칭 기능 추가 가능할까요!?

### ISSUE THREAD

**Issue by jminstudio** [jellyhani/League-of-Legends-rankgame-nickname-spy#13]
![스크린샷 2024-06-03 134413](https://github.com/jellyhani/League-of-Legends-rankgame-nickname-spy/assets/171535633/3bff64eb-a048-454f-83f4-7ee10d304a50)

이거 너무 잘쓰고있는데, 오토매칭 기능, 이 프로그램에도 추가됐으면합니다.!!

**Comment by jellyhani** [comment]
빠른 시일 내에 업데이트 하겠습니다

**Comment by jellyhani** [comment]
완
