### ISSUE TITLE
게임을 시작하면 멀티서치가 자동으로 꺼집니다.

### ISSUE THREAD

**Issue by Fortheantalian** [jellyhani/League-of-Legends-rankgame-nickname-spy#2]
매 게임마다 켜줘야 하는 번거로움이 있는데.. 어떻게 해결해야할까요?

**Comment by jellyhani** [comment]
프로그램이 꺼질때 클립보드에 에러로그가 복사 될거에요 그 에러로그좀 붙여넣기로 보여주시겠어요? 제가 테스트할때는 꺼지는 경우가 없었어서요

**Comment by Fortheantalian** [comment]
'statusThread' object has no attribute 'riot_api' 이렇게 뜨네요, 인게임 딱 들어가는 순간 자동으로 꺼지더군요.

**Comment by jellyhani** [comment]
그러면 LCU Api 를 사용하기 위한 정보를 아에 못불러왔을텐데 전적검색이나 채팅로그 또는 현재 어느 세션에 있는지 정보는 받아와졌었나요??

혹시 인게임 들어갈때 클라이언트가 꺼지게 설정하셨나요?

**Comment by Fortheantalian** [comment]
클라이언트 안꺼지게 하니까 잘 되네요 시간내주셔서 감사합니다.
