### ISSUE TITLE
명령 프롬프트 비스무리한거에서 에러가 뜨네요

### ISSUE THREAD

**Issue by Fortheantalian** [jellyhani/League-of-Legends-rankgame-nickname-spy#4]
Error: Invalid URL '/lol-gameflow/v1/gameflow-phase': No scheme supplied. Perhaps you meant https:///lol-gameflow/v1/gameflow-phase?

이렇게 4번정도 뜹니다만 작동은 이상 없는걸로 보입니다. 가장 최신버전만 이런 형상이 발생하는데 확인 부탁드립니다.

/ 인게임에서 멀티서치가 켜져있는경우 프레임 드랍이 심하게 발생하는데 이를 고칠 방법이 있을까요?

항상 잘쓰고 있습니다. 계속 업데이트 해주셔서 정말 고마워요.

**Comment by jellyhani** [comment]
1. 롤 세션 정보를 가져오는 과정에서 현재 받아올 수 있는 정보가 없을때 뜨는 경우입니다.

본래 https://127.0.0.1:port/lol-gameflow/v1/gameflow-phase 에 접속하여 정보를 받아와야하는데
아직 클라이언트에서 정보를 받아오는 중 127.0.0.1:port 이 부분에 대한 정보가 없어서  https:///lol-gameflow/v1/gameflow-phase 로 연결되서 그래요

큰 문제 없는 에러입니다.

2. 확인해보겠습니다.
