### ISSUE TITLE
함께 올라오는 소스코드 최신화가 되어있는게 맞을까요 ?

### ISSUE THREAD

**Issue by surplusboy** [jellyhani/League-of-Legends-rankgame-nickname-spy#5]
안되어 있는 것 같아서 여쭙습니다 . . .

**Comment by jellyhani** [comment]
최신화 안하고 있긴해요
14.1 패치 넘어오면서 채팅기록 보는거까지 저격패치 당한거 같아서요

**Comment by surplusboy** [comment]
그럼 현재 버젼의 소스코드는 올리실 예정이 없으신걸까요 ?

**Comment by surplusboy** [comment]
> 최신화 안하고 있긴해요 14.1 패치 넘어오면서 채팅기록 보는거까지 저격패치 당한거 같아서요

그럼 현재 버젼의 소스코드는 올리실 예정이 없으신걸까요 ?

**Comment by jellyhani** [comment]
일부 코드 가린상태로 올려드릴게요

**Comment by surplusboy** [comment]
> 일부 코드 가린상태로 올려드릴게요

넵 그 정도면 충분할 것 같습니다. 감사합니다.
