### ISSUE TITLE
누가 심술두꺼비고 누가 어스름늑대인지 표시되면 더 좋을 것 같습니다.

### ISSUE THREAD

**Issue by L0KKaa1** [jellyhani/League-of-Legends-rankgame-nickname-spy#6]
아군 서포터 챔피언 풀을 보고 원딜을 고르고 싶은데 지금은 전적을 하나하나 보면서 서포터에 해당하는 유저가 누구인지 찾고 있습니다. 제목처럼 더 상세하게 표기되면 좋을 것 같습니다. 감사합니다.

**Comment by jellyhani** [comment]
현재로선 채팅 유도 말곤 방법을 찾지 못했습니다.
게임수락 - 인터넷 연결 해제 - 잠시후 재연결 시 클라이언트에서 소환사 이름을 숨기지 않아 확인이 가능하나 현재로선 api 에선 제공하지 않으므로 클라이언트를 건드려야하는데.. 위험이 더 커지므로 다른 방법을 찾을 시 기능 제공하겠습니다.

**Comment by L0KKaa1** [comment]
아 제공하지 않는 부분이었군요. 답변 고맙습니다.
