### ISSUE TITLE
프롬프트 에러 어떻게해결하나요 ?

### ISSUE THREAD

**Issue by gfwoong789** [jellyhani/League-of-Legends-rankgame-nickname-spy#7]
Invalid URL '/lol-gameflow/v1/gameflow-phase': No scheme supplied. Perhaps you meant https:///lol-gameflow/v1/gameflow-phase?
1.사진과 같이 메세지가 반복해서 뜨네요. 전적을 볼수없는데 어떻게 해결할수 있을까요? 
2.딥롤로 항상 보고싶은데 저장기능 없을까요 ?
항상잘쓰고있습니다 감사합니다.
![4444](https://github.com/jellyhani/League-of-Legends-rankgame-nickname-spy/assets/159990671/7d89ed6f-a311-4989-b864-95b080e63a54)
![4444](https://github.com/jellyhani/League-of-Legends-rankgame-nickname-spy/assets/159990671/b0728077-e2ee-4c60-847d-a807009afbb7)

**Comment by jellyhani** [comment]
1. 롤 클라이언트에서 토큰을 받아오지 못하는 경우네요. 무엉가 문제가 있긴한건데 어느경우에 나온건지 확인이 필요합니다
2. 저장기능 2.9버전 업데이트할때 넣겟습니다

**Comment by jellyhani** [comment]
2. 저장기능 업데이트 완
