### ISSUE TITLE
멀티서치를 키게되면 자동으로 프롬프트가 켜지게되고 프롬프트를 닫으면 멀티서치도 닫힙니다.

### ISSUE THREAD

**Issue by Fortheantalian** [jellyhani/League-of-Legends-rankgame-nickname-spy#8]
프롬프트를 키치 않고 멀티서치만 사용하고 싶은데 방법이 없을련지요? 롤부터 멀티서치, 프롬프트 까지 켜지니 창이 너무 많아지네요..

**Comment by jellyhani** [comment]
프롬프트가 안열리게 프로그램을 제작하면 윈도우 디펜더에서 바이러스로 판단하고 자꾸 파일을 지우더라구요
임시대책으로 열리게 만든거라 추 후 다른방법 생기면 다시 프로그램만 켜지게 해드릴게요 아니면 이번버전은 임시로 만들어 드릴 순 있는데
실시간보호는 끄셔야할거에요.

**Comment by Fortheantalian** [comment]
좀더 기다려 봐야겠군요
