### ISSUE TITLE
0초 닷지 스펠바꾸는 기능 없애거나 끌수 있게 만들어주실수있나요?

### ISSUE THREAD

**Issue by woscc123** [jellyhani/League-of-Legends-rankgame-nickname-spy#9]
닷지하면 바뀐 스펠로 저장이 되서 없애는게 더 좋을거같습니다 .D랑 F가 바뀌어서 좋은점이 딱히없는거같습니다

**Comment by jellyhani** [comment]
스펠 바꾸는걸 없애면 클라이언트에서 시간을 못불러와서 0초에 닷지 못해요
옛버전처럼 10명 모두 픽하기 전에 해야하는데 .. 조건문 다시 달기는 귀찮으니 다른 방법 생각해볼게요
